# Generated by Django 3.0.8 on 2020-07-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
